version: '3.1'
services:
  mariadb:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: 'spinitron2_test'
      MYSQL_ROOT_PASSWORD: ''
  web:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/v2
